using System.Collections.Generic;

namespace StockClosenessAI
{
    // A simple class to hold the information for each company
    public class CompanyInfo
    {
        public string Industry { get; }
        public string Description { get; }

        public CompanyInfo(string industry, string description)
        {
            Industry = industry;
            Description = description;
        }
    }

    public static class CompanyDescriptions
    {
        // The dictionary maps Ticker (string) to CompanyInfo object
        public static readonly Dictionary<string, CompanyInfo> Descriptions = new Dictionary<string, CompanyInfo>
        {
            // --- 💻 Information Technology & Communication Services ---
            {"AAPL", new CompanyInfo("Technology", "Multinational technology company focused on consumer electronics, software, and online services (Apple)")},
            {"MSFT", new CompanyInfo("Technology", "Global technology company, developing software, electronics, and cloud services (Microsoft)")},
            {"GOOGL", new CompanyInfo("Communication Services", "Global technology conglomerate, parent company of Google, focused on search, cloud, and AI (Alphabet Inc. Class A)")},
            {"GOOG", new CompanyInfo("Communication Services", "Global technology conglomerate, parent company of Google, focused on search, cloud, and AI (Alphabet Inc. Class C)")},
            {"NVDA", new CompanyInfo("Technology", "Designer of graphics processing units (GPUs) and AI computing platforms (NVIDIA)")},
            {"META", new CompanyInfo("Communication Services", "Technology conglomerate, owner of Facebook, Instagram, and WhatsApp (Meta Platforms)")},
            {"TSM", new CompanyInfo("Technology", "Taiwanese multinational semiconductor manufacturing company (TSMC ADR)")},
            {"AVGO", new CompanyInfo("Technology", "Global infrastructure technology company, designing and developing semiconductors and software (Broadcom)")},
            {"TCEHY", new CompanyInfo("Communication Services", "Chinese multinational technology and entertainment conglomerate (Tencent Holdings ADR)")},
            {"ORCL", new CompanyInfo("Technology", "Enterprise software, cloud applications, and database technology (Oracle)")},
            {"CSCO", new CompanyInfo("Technology", "Multinational technology conglomerate that develops, manufactures, and sells networking hardware and telecommunications equipment (Cisco Systems)")},
            {"INTC", new CompanyInfo("Technology", "Multinational corporation and technology company primarily known for its microprocessors and semiconductor chips (Intel)")},
            {"QCOM", new CompanyInfo("Technology", "Semiconductor and telecommunications equipment company (Qualcomm)")},
            {"TXN", new CompanyInfo("Technology", "Designer and manufacturer of semiconductors and integrated circuits (Texas Instruments)")},
            {"ADBE", new CompanyInfo("Technology", "Software company focused on multimedia and creativity software products (Adobe)")},
            {"CRM", new CompanyInfo("Technology", "Cloud-based software company specializing in customer relationship management (Salesforce)")},
            {"ASML", new CompanyInfo("Technology", "Dutch company providing photolithography systems for semiconductor manufacturing (ASML ADR)")},
            {"NFLX", new CompanyInfo("Communication Services", "Subscription streaming service and production company (Netflix)")},
            {"NOW", new CompanyInfo("Technology", "Cloud computing company providing digital workflow solutions (ServiceNow)")},
            {"ADSK", new CompanyInfo("Technology", "Software and services for architecture, engineering, and manufacturing (Autodesk)")},
            {"EA", new CompanyInfo("Communication Services", "Video game company (Electronic Arts)")},
            {"T", new CompanyInfo("Communication Services", "Telecommunications company (AT&T)")},
            {"VZ", new CompanyInfo("Communication Services", "Telecommunications and wireless provider (Verizon Communications)")},
            {"WDAY", new CompanyInfo("Technology", "On-demand financial management and human capital management software (Workday)")},
            {"DDOG", new CompanyInfo("Technology", "Cloud-scale monitoring and analytics platform (Datadog)")},
            {"MCHP", new CompanyInfo("Technology", "Microcontroller and semiconductor solutions (Microchip Technology)")},
            {"HPQ", new CompanyInfo("Technology", "Personal computers and printing products (HP Inc.)")},
            {"ZBRA", new CompanyInfo("Technology", "Mobile computing, data capture, and printing solutions (Zebra Technologies)")},
            {"STX", new CompanyInfo("Technology", "Data storage and management solutions (Seagate Technology)")},
            {"MU", new CompanyInfo("Technology", "Semiconductor company specializing in computer memory and data storage (Micron Technology)")},
            {"VMW", new CompanyInfo("Technology", "Cloud computing and virtualization technology (VMware - often being acquired or delisted)")},
            {"ERIC", new CompanyInfo("Communication Services", "Swedish multinational telecommunications company (Ericsson ADR)")},
            {"PANW", new CompanyInfo("Technology", "Cybersecurity platform and network security (Palo Alto Networks)")},
            {"SNOW", new CompanyInfo("Technology", "Cloud-based data warehousing platform (Snowflake Inc.)")},
            {"SHOP", new CompanyInfo("Technology", "E-commerce platform for online stores and retail point-of-sale systems (Shopify)")},
            {"FIS", new CompanyInfo("Technology", "Financial services technology (Fidelity National Information Services) - Listed under Tech due to focus on systems")},
            {"SPS", new CompanyInfo("Technology", "Power management solutions (Sensata Technologies) - Listed under Tech due to product focus")},
            {"SAP", new CompanyInfo("Technology", "German multinational software company, known for enterprise resource planning (SAP SE ADR)")},
            {"GPN", new CompanyInfo("Technology", "Payment technology company (Global Payments) - Classified as Tech for its solutions focus")},
            {"CHTR", new CompanyInfo("Communication Services", "Telecommunications and media company (Charter Communications)")},
            {"VZIO", new CompanyInfo("Communication Services", "Consumer electronics and smart TV platform (Vizio Holding Corp)")},
            {"WDC", new CompanyInfo("Technology", "Computer data storage company (Western Digital Corporation)")},
            {"FSLR", new CompanyInfo("Technology", "Solar panel manufacturing and power plant construction (First Solar, Inc.) - Classified as Tech for product focus")},
            {"OKTA", new CompanyInfo("Technology", "Cloud-based identity and access management (Okta, Inc.)")},
            {"DOCU", new CompanyInfo("Technology", "Electronic signature and digital transaction management (DocuSign, Inc.)")},
            {"FTNT", new CompanyInfo("Technology", "Cybersecurity solutions (Fortinet, Inc.)")},
            {"CDNS", new CompanyInfo("Technology", "Electronic design automation (Cadence Design Systems, Inc.)")},
            {"ANSS", new CompanyInfo("Technology", "Engineering simulation software (Ansys, Inc.)")},
            {"HUBS", new CompanyInfo("Technology", "Marketing, sales, and service software (HubSpot, Inc.)")},
            {"TWLO", new CompanyInfo("Technology", "Cloud communications platform (Twilio Inc.)")},
            {"TEAM", new CompanyInfo("Technology", "Software for development and team collaboration (Atlassian Corporation Plc)")},
            {"RNG", new CompanyInfo("Communication Services", "Cloud-based communications provider (RingCentral, Inc.)")},
            {"ZM", new CompanyInfo("Technology", "Video conferencing software (Zoom Video Communications, Inc.)")},
            {"AZPN", new CompanyInfo("Technology", "Industrial software and AI (Aspen Technology, Inc.)")},

            // --- 💊 Healthcare & Pharmaceuticals ---
            {"LLY", new CompanyInfo("Healthcare", "Pharmaceutical company focused on neuroscience, endocrinology, and oncology (Eli Lilly)")},
            {"JNJ", new CompanyInfo("Healthcare", "Pharmaceutical, medical device, and consumer health company (Johnson & Johnson)")},
            {"UNH", new CompanyInfo("Healthcare", "Diversified healthcare company, insurance, and health services (UnitedHealth Group)")},
            {"PFE", new CompanyInfo("Healthcare", "Biopharmaceutical company researching and developing medicines and vaccines (Pfizer)")},
            {"MRK", new CompanyInfo("Healthcare", "Pharmaceutical company developing therapies for cancer, infectious diseases, and vaccines (Merck & Co.)")},
            {"ABBV", new CompanyInfo("Healthcare", "Biopharmaceutical company focusing on immunology, oncology, and neuroscience (AbbVie)")},
            {"NVO", new CompanyInfo("Healthcare", "Danish pharmaceutical company specializing in diabetes and obesity treatments (Novo Nordisk ADR)")},
            {"TMO", new CompanyInfo("Healthcare", "Scientific instrument, consumables, and software company (Thermo Fisher Scientific)")},
            {"DHR", new CompanyInfo("Healthcare", "Science and technology conglomerate specializing in life sciences and diagnostics (Danaher Corporation)")},
            {"ABT", new CompanyInfo("Healthcare", "Medical devices, diagnostics, and nutritional products (Abbott Laboratories)")},
            {"BMY", new CompanyInfo("Healthcare", "Pharmaceutical company specializing in cancer, HIV/AIDS, and cardiovascular disease (Bristol Myers Squibb)")},
            {"SYK", new CompanyInfo("Healthcare", "Medical technology company, implants and surgical instruments (Stryker)")},
            {"ZTS", new CompanyInfo("Healthcare", "Animal health medicines and vaccines (Zoetis)")},
            {"EW", new CompanyInfo("Healthcare", "Medical equipment company focused on heart valves (Edwards Lifesciences)")},
            {"BAX", new CompanyInfo("Healthcare", "Healthcare products, including medical devices and pharmaceuticals (Baxter International)")},
            {"BDX", new CompanyInfo("Healthcare", "Medical technology company (Becton, Dickinson and Co.)")},
            {"VEEV", new CompanyInfo("Technology", "Cloud computing solutions for the global life sciences industry (Veeva Systems) - Listed under Tech due to primary product type")},
            {"MCK", new CompanyInfo("Healthcare", "Pharmaceutical distributor and healthcare IT solutions (McKesson Corporation)")},
            {"HCA", new CompanyInfo("Healthcare", "Healthcare facilities operator (HCA Healthcare)")},
            {"ELV", new CompanyInfo("Healthcare", "Managed healthcare and insurance (Elevance Health, formerly Anthem)")},
            {"OGN", new CompanyInfo("Healthcare", "Pharmaceuticals and healthcare solutions (Organon & Co.)")},
            {"CVS", new CompanyInfo("Healthcare", "Health solutions company, operating pharmacies and insurance (CVS Health)")},
            {"GILD", new CompanyInfo("Healthcare", "Biopharmaceutical company focusing on HIV, liver diseases, and oncology (Gilead Sciences)")},
            {"ISRG", new CompanyInfo("Technology", "Manufacturer of the Da Vinci surgical systems (Intuitive Surgical) - Listed under Tech due to robotics/hardware focus")},
            {"SNY", new CompanyInfo("Healthcare", "Global pharmaceutical and healthcare company (Sanofi ADR - France)")},
            {"NVS", new CompanyInfo("Healthcare", "Pharmaceutical and medical technology company (Novartis ADR - Switzerland)")},
            {"AZN", new CompanyInfo("Healthcare", "British-Swedish multinational pharmaceutical and biotechnology company (AstraZeneca PLC ADR)")},
            {"ZBH", new CompanyInfo("Healthcare", "Medical device company, orthopedic products (Zimmer Biomet Holdings, Inc.)")},
            {"HOLX", new CompanyInfo("Healthcare", "Medical technology company, primarily women's health (Hologic, Inc.)")},
            {"RMD", new CompanyInfo("Healthcare", "Medical equipment for respiratory conditions (ResMed Inc.)")},
            {"ICLR", new CompanyInfo("Healthcare", "Clinical research organization (ICON plc)")},
            {"LH", new CompanyInfo("Healthcare", "Clinical laboratory services (Labcorp)")},
            {"DGX", new CompanyInfo("Healthcare", "Clinical laboratory services (Quest Diagnostics Incorporated)")},
            {"AMGN", new CompanyInfo("Healthcare", "Biotechnology company (Amgen Inc.)")},
            {"BIIB", new CompanyInfo("Healthcare", "Biotechnology company, neuroscience (Biogen Inc.)")},
            {"INCY", new CompanyInfo("Healthcare", "Biopharmaceutical company (Incyte Corporation)")},
            {"UHS", new CompanyInfo("Healthcare", "Hospital management company (Universal Health Services, Inc.)")},
            {"TFX", new CompanyInfo("Healthcare", "Medical device company (Teleflex Incorporated)")},

            // --- 🏦 Financials ---
            {"BRK-B", new CompanyInfo("Financials", "Conglomerate with diverse holdings across insurance, freight, energy, and consumer products (Berkshire Hathaway Class B)")},
            {"JPM", new CompanyInfo("Financials", "Global financial services firm and investment bank (JPMorgan Chase)")},
            {"V", new CompanyInfo("Financials", "Global payments technology company (Visa)")},
            {"MA", new CompanyInfo("Financials", "Global payments technology company (Mastercard)")},
            {"BAC", new CompanyInfo("Financials", "Bank holding company, commercial and investment banking (Bank of America)")},
            {"WFC", new CompanyInfo("Financials", "Diversified financial services company, banking, insurance, and investment (Wells Fargo)")},
            {"GS", new CompanyInfo("Financials", "Global investment banking, securities, and investment management firm (Goldman Sachs)")},
            {"MS", new CompanyInfo("Financials", "Global financial services firm, investment banking and wealth management (Morgan Stanley)")},
            {"AXP", new CompanyInfo("Financials", "Multinational financial services corporation, known for its credit cards and travel services (American Express)")},
            {"C", new CompanyInfo("Financials", "Global bank and financial services corporation (Citigroup)")},
            {"BLK", new CompanyInfo("Financials", "Global investment management corporation (BlackRock)")},
            {"SPGI", new CompanyInfo("Financials", "Financial information and analytics, including S&P credit ratings (S&P Global)")},
            {"MMC", new CompanyInfo("Financials", "Global professional services firm, risk, strategy, and people solutions (Marsh McLennan)")},
            {"SCHW", new CompanyInfo("Financials", "Financial services, banking, investment advice (Charles Schwab)")},
            {"TFC", new CompanyInfo("Financials", "Financial holding company (Truist Financial Corporation)")},
            {"USB", new CompanyInfo("Financials", "Financial services, commercial and retail banking (U.S. Bancorp)")},
            {"COF", new CompanyInfo("Financials", "Bank holding company specializing in credit cards and financial products (Capital One)")},
            {"PNC", new CompanyInfo("Financials", "Financial services, retail and business banking (PNC Financial Services)")},
            {"AIG", new CompanyInfo("Financials", "Multinational finance and insurance corporation (American International Group)")},
            {"TRV", new CompanyInfo("Financials", "Multinational insurance company (The Travelers Companies)")},
            {"CB", new CompanyInfo("Financials", "Insurance, reinsurance, and financial services (Chubb Limited)")},
            {"CME", new CompanyInfo("Financials", "Financial derivatives exchange (CME Group)")},
            {"ICE", new CompanyInfo("Financials", "Global exchange and clearing house (Intercontinental Exchange)")},
            {"AJG", new CompanyInfo("Financials", "Insurance brokerage and risk management (Arthur J. Gallagher & Co.)")},
            {"MET", new CompanyInfo("Financials", "Insurance and financial services (MetLife)")},
            {"ALL", new CompanyInfo("Financials", "Personal and commercial property-casualty insurer (Allstate)")},
            {"PRU", new CompanyInfo("Financials", "Financial services and insurance (Prudential Financial)")},
            {"RY", new CompanyInfo("Financials", "Financial services company (Royal Bank of Canada ADR)")},
            {"RE", new CompanyInfo("Financials", "Global reinsurance company (Everest Re Group)")},
            {"L", new CompanyInfo("Financials", "Canadian life insurance and financial services company (Manulife Financial Corp)")},
            {"MFC", new CompanyInfo("Financials", "Canadian multinational insurance company and financial services provider (Manulife Financial Corp - US listing)")},
            {"BNS", new CompanyInfo("Financials", "Canadian multinational banking and financial services company (Bank of Nova Scotia)")},
            {"TD", new CompanyInfo("Financials", "Canadian multinational bank and financial services company (Toronto-Dominion Bank)")},
            {"UBS", new CompanyInfo("Financials", "Swiss multinational investment bank and financial services company (UBS Group AG ADR)")},
            {"HDB", new CompanyInfo("Financials", "Indian multinational banking and financial services company (HDFC Bank Ltd ADR)")},
            {"AGNC", new CompanyInfo("Financials", "Real estate investment trust (REIT) managing mortgage-backed securities (AGNC Investment Corp.)")},
            {"APAM", new CompanyInfo("Financials", "Investment management firm (Artisan Partners Asset Management Inc.)")},
            {"BEN", new CompanyInfo("Financials", "Investment management company (Franklin Resources, Inc.)")},
            {"SEIC", new CompanyInfo("Financials", "Financial services and technology company (SEI Investments Company)")},
            {"AMG", new CompanyInfo("Financials", "Global asset management company (Affiliated Managers Group, Inc.)")},
            {"MSCI", new CompanyInfo("Financials", "Global provider of financial services, including indexes and analytics (MSCI Inc.)")},
            {"NDAQ", new CompanyInfo("Financials", "Exchange and technology provider (Nasdaq, Inc.)")},
            {"LPLA", new CompanyInfo("Financials", "Broker-dealer and investment advisor (LPL Financial Holdings Inc.)")},
            {"DFS", new CompanyInfo("Financials", "Direct banking and payment services company (Discover Financial Services)")},
            {"KEY", new CompanyInfo("Financials", "Regional bank holding company (KeyCorp)")},
            {"FITB", new CompanyInfo("Financials", "Regional bank holding company (Fifth Third Bancorp)")},
            {"HBAN", new CompanyInfo("Financials", "Regional bank holding company (Huntington Bancshares Incorporated)")},
            {"CMA", new CompanyInfo("Financials", "Regional bank holding company (Comerica Incorporated)")},
            {"WAL", new CompanyInfo("Financials", "Commercial bank (Western Alliance Bancorporation)")},
            {"CFR", new CompanyInfo("Financials", "Bank holding company (Cullen/Frost Bankers, Inc.)")},
            {"FDS", new CompanyInfo("Financials", "Financial data and software (FactSet Research Systems Inc.)")},
            {"BIPC", new CompanyInfo("Financials", "Asset management business focused on infrastructure (Brookfield Infrastructure Partners Corporation)")},
            {"BAM", new CompanyInfo("Financials", "Global asset manager (Brookfield Asset Management Ltd.)")},

            // --- ⛽ Energy & Basic Materials ---
            {"XOM", new CompanyInfo("Energy", "Multinational oil and gas corporation (Exxon Mobil)")},
            {"CVX", new CompanyInfo("Energy", "Multinational energy corporation (Chevron)")},
            {"SHEL", new CompanyInfo("Energy", "Multinational oil and gas company (Shell PLC ADR)")},
            {"BP", new CompanyInfo("Energy", "Multinational oil and gas company (BP PLC ADR)")},
            {"DOW", new CompanyInfo("Materials", "Multinational chemical corporation")},
            {"LIN", new CompanyInfo("Materials", "Global industrial gas and engineering company (Linde PLC)")},
            {"APD", new CompanyInfo("Materials", "Industrial gases and chemicals (Air Products & Chemicals)")},
            {"DD", new CompanyInfo("Materials", "Specialty chemical and materials company (DuPont de Nemours)")},
            {"BHP", new CompanyInfo("Materials", "Global resources company, mining iron ore, copper, and petroleum (BHP Group ADR)")},
            {"RIO", new CompanyInfo("Materials", "Metals and mining company (Rio Tinto ADR)")},
            {"KMI", new CompanyInfo("Energy", "Energy infrastructure company, pipelines and terminals (Kinder Morgan)")},
            {"WMB", new CompanyInfo("Energy", "Energy infrastructure, natural gas pipelines (Williams Companies)")},
            {"DVN", new CompanyInfo("Energy", "Independent oil and gas exploration and production company (Devon Energy)")},
            {"PXD", new CompanyInfo("Energy", "Independent oil and gas exploration and production company (Pioneer Natural Resources)")},
            {"AMCR", new CompanyInfo("Materials", "Global packaging company (Amcor PLC)")},
            {"ECL", new CompanyInfo("Materials", "Water treatment, industrial process, and energy technologies (Ecolab)")},
            {"MOS", new CompanyInfo("Materials", "Phosphate and potash nutrient company (The Mosaic Company)")},
            {"NTR", new CompanyInfo("Materials", "Agricultural products, including potash, nitrogen, and phosphate (Nutrien Ltd.)")},
            {"CLF", new CompanyInfo("Materials", "Iron ore and steel producer (Cleveland-Cliffs)")},
            {"NUE", new CompanyInfo("Materials", "Steel and fabricated metal products (Nucor Corporation)")},
            {"FCX", new CompanyInfo("Materials", "International mining company, primarily copper and gold (Freeport-McMoRan)")},
            {"CEIX", new CompanyInfo("Energy", "Coal mining company (Consol Energy Inc.)")},
            {"HAL", new CompanyInfo("Energy", "Oilfield services company (Halliburton Co.)")},
            {"SUZ", new CompanyInfo("Materials", "Pulp and paper company (Suzano S.A. ADR - Brazil)")},
            {"PTR", new CompanyInfo("Energy", "Chinese integrated oil and gas company (PetroChina Company Limited ADR)")},
            {"SID", new CompanyInfo("Materials", "Brazilian steel manufacturer (Companhia Siderúrgica Nacional ADR)")},
            {"STLD", new CompanyInfo("Materials", "Steel producer and metals recycler (Steel Dynamics, Inc.)")},
            {"VMC", new CompanyInfo("Materials", "Construction aggregates and materials (Vulcan Materials Company)")},
            {"MLM", new CompanyInfo("Materials", "Construction aggregates and materials (Martin Marietta Materials, Inc.)")},
            {"NEM", new CompanyInfo("Materials", "Gold mining company (Newmont Corporation)")},
            {"FNV", new CompanyInfo("Materials", "Gold-focused streaming and royalty company (Franco-Nevada Corporation)")},
            {"MEOH", new CompanyInfo("Materials", "Methanol and related chemicals production (Methanex Corporation)")},
            {"WRK", new CompanyInfo("Materials", "Paper and packaging company (WestRock Company)")},
            {"SEE", new CompanyInfo("Materials", "Protective packaging solutions (Sealed Air Corporation)")},

            // --- 🛍️ Consumer Discretionary & Staples ---
            {"AMZN", new CompanyInfo("Consumer Discretionary", "E-commerce, cloud computing (AWS), digital streaming, and artificial intelligence (Amazon)")},
            {"TSLA", new CompanyInfo("Consumer Discretionary", "Electric vehicles, battery storage, and solar products (Tesla)")},
            {"WMT", new CompanyInfo("Consumer Staples", "Global retail and wholesale company (Walmart)")},
            {"HD", new CompanyInfo("Consumer Discretionary", "Home improvement retailer (Home Depot)")},
            {"COST", new CompanyInfo("Consumer Staples", "Membership warehouse club retailer (Costco Wholesale)")},
            {"PG", new CompanyInfo("Consumer Staples", "Consumer goods company, personal care and household products (Procter & Gamble)")},
            {"KO", new CompanyInfo("Consumer Staples", "Beverage company (Coca-Cola)")},
            {"PEP", new CompanyInfo("Consumer Staples", "Beverage and food company (PepsiCo)")},
            {"MCD", new CompanyInfo("Consumer Discretionary", "Fast-food restaurant chain (McDonald's)")},
            {"NKE", new CompanyInfo("Consumer Discretionary", "Athletic footwear and apparel company (Nike)")},
            {"SBUX", new CompanyInfo("Consumer Discretionary", "Multinational coffeehouse chain (Starbucks)")},
            {"TGT", new CompanyInfo("Consumer Discretionary", "Retail corporation, operating mass merchandise stores (Target)")},
            {"LOW", new CompanyInfo("Consumer Discretionary", "Home improvement retailer (Lowe's Companies)")},
            {"CL", new CompanyInfo("Consumer Staples", "Consumer products company, focusing on oral, personal, and home care (Colgate-Palmolive)")},
            {"PM", new CompanyInfo("Consumer Staples", "Tobacco company (Philip Morris International)")},
            {"MO", new CompanyInfo("Consumer Staples", "Tobacco and wine company (Altria Group)")},
            {"HLT", new CompanyInfo("Consumer Discretionary", "Global hospitality company (Hilton Worldwide Holdings)")},
            {"CHWY", new CompanyInfo("Consumer Discretionary", "E-commerce retailer of pet food and products (Chewy)")},
            {"BTI", new CompanyInfo("Consumer Staples", "Global tobacco company (British American Tobacco ADR)")},
            {"STZ", new CompanyInfo("Consumer Staples", "Beer, wine, and spirits producer (Constellation Brands)")},
            {"DPZ", new CompanyInfo("Consumer Discretionary", "Pizza delivery chain (Domino's Pizza)")},
            {"YUM", new CompanyInfo("Consumer Discretionary", "Fast food restaurant company (Yum! Brands)")},
            {"CMG", new CompanyInfo("Consumer Discretionary", "Fast casual restaurants (Chipotle Mexican Grill)")},
            {"RCL", new CompanyInfo("Consumer Discretionary", "Global cruise company (Royal Caribbean Group)")},
            {"LULU", new CompanyInfo("Consumer Discretionary", "Athletic apparel company (Lululemon Athletica Inc.)")},
            {"BKNG", new CompanyInfo("Consumer Discretionary", "Online travel and reservation services (Booking Holdings)")},
            {"MAR", new CompanyInfo("Consumer Discretionary", "Multinational hospitality company (Marriott International)")},
            {"ABNB", new CompanyInfo("Consumer Discretionary", "Online marketplace for lodging and tourism activities (Airbnb, Inc.)")},
            {"MELI", new CompanyInfo("Consumer Discretionary", "E-commerce and financial services platform in Latin America (MercadoLibre)")},
            {"TM", new CompanyInfo("Consumer Discretionary", "Multinational automotive manufacturer (Toyota Motor Corporation ADR - Japan)")},
            {"LVMUY", new CompanyInfo("Consumer Discretionary", "Luxury goods conglomerate (LVMH Moët Hennessey Louis Vuitton ADR - France)")},
            {"BABA", new CompanyInfo("Consumer Discretionary", "Chinese multinational e-commerce, retail, Internet, and technology conglomerate (Alibaba Group Holding Ltd ADR)")},
            {"CUK", new CompanyInfo("Consumer Discretionary", "Global cruise company (Carnival Corporation & PLC - UK/US listing)")},
            {"HMC", new CompanyInfo("Consumer Discretionary", "Japanese multinational automotive manufacturer (Honda Motor Co., Ltd. ADR)")},
            {"EXPE", new CompanyInfo("Consumer Discretionary", "Online travel shopping company (Expedia Group)")},
            {"PENN", new CompanyInfo("Consumer Discretionary", "Gaming and racing operations (PENN Entertainment, Inc.)")},
            {"MGM", new CompanyInfo("Consumer Discretionary", "Global hospitality and entertainment company (MGM Resorts International)")},
            {"WYNN", new CompanyInfo("Consumer Discretionary", "Luxury resorts and casino hotels (Wynn Resorts, Limited)")},
            {"LVS", new CompanyInfo("Consumer Discretionary", "Integrated resorts and casinos (Las Vegas Sands Corp.)")},
            {"TJX", new CompanyInfo("Consumer Discretionary", "Off-price department store chain (The TJX Companies, Inc.)")},
            {"ROST", new CompanyInfo("Consumer Discretionary", "Off-price retailer (Ross Stores, Inc.)")},
            {"KSS", new CompanyInfo("Consumer Discretionary", "Department store retail (Kohl's Corporation)")},
            {"GES", new CompanyInfo("Consumer Discretionary", "Apparel and accessories retailer (Guess?, Inc.)")},
            {"BURL", new CompanyInfo("Consumer Discretionary", "Off-price department store chain (Burlington Stores, Inc.)")},
            {"DG", new CompanyInfo("Consumer Discretionary", "Discount retail stores (Dollar General)")},
            {"DLTR", new CompanyInfo("Consumer Discretionary", "Discount retail stores (Dollar Tree)")},
            {"KDP", new CompanyInfo("Consumer Staples", "Coffee and beverage company (Keurig Dr Pepper Inc.)")},
            {"KHC", new CompanyInfo("Consumer Staples", "Food and beverage company (The Kraft Heinz Company)")},
            {"GIS", new CompanyInfo("Consumer Staples", "Manufacturer of branded consumer foods (General Mills, Inc.)")},
            {"CPB", new CompanyInfo("Consumer Staples", "Canned soup and other food products (Campbell Soup Company)")},
            {"HRL", new CompanyInfo("Consumer Staples", "Food processing company (Hormel Foods Corporation)")},
            {"BG", new CompanyInfo("Consumer Staples", "Global agribusiness and food company (Bunge Global SA)")},
            {"ADM", new CompanyInfo("Consumer Staples", "Global food processing and commodities trading corporation (Archer-Daniels-Midland Company)")},

            // --- 🛠️ Industrials & Infrastructure ---
            {"CAT", new CompanyInfo("Industrials", "Manufacturer of construction and mining equipment, diesel and natural gas engines, industrial gas turbines (Caterpillar)")},
            {"MMM", new CompanyInfo("Industrials", "Multinational conglomerate operating in industry, worker safety, health care, and consumer goods (3M Company)")},
            {"LMT", new CompanyInfo("Industrials", "Global aerospace, defense, security, and advanced technologies company (Lockheed Martin)")},
            {"BA", new CompanyInfo("Industrials", "Multinational aerospace and defense corporation (Boeing)")},
            {"RTX", new CompanyInfo("Industrials", "Aerospace and defense company (RTX Corporation, formerly Raytheon Technologies)")},
            {"HON", new CompanyInfo("Industrials", "Multinational conglomerate operating in aerospace, building technologies, and performance materials (Honeywell)")},
            {"GE", new CompanyInfo("Industrials", "Digital industrial company operating in power, renewable energy, and aviation (General Electric)")},
            {"WM", new CompanyInfo("Industrials", "Waste management and environmental services (Waste Management)")},
            {"ROK", new CompanyInfo("Industrials", "Industrial automation and information services (Rockwell Automation)")},
            {"FDX", new CompanyInfo("Industrials", "Multinational courier delivery services company (FedEx)")},
            {"UPS", new CompanyInfo("Industrials", "Global package delivery and supply chain management (UPS)")},
            {"DAL", new CompanyInfo("Industrials", "Major American airline (Delta Air Lines)")},
            {"PH", new CompanyInfo("Industrials", "Diversified industrial manufacturer (Parker-Hannifin)")},
            {"EMR", new CompanyInfo("Industrials", "Global technology and engineering company (Emerson Electric)")},
            {"PCAR", new CompanyInfo("Industrials", "Premium commercial vehicles manufacturer (PACCAR)")},
            {"ODFL", new CompanyInfo("Industrials", "Less-than-truckload (LTL) shipping (Old Dominion Freight Line)")},
            {"JCI", new CompanyInfo("Industrials", "Building products and technologies (Johnson Controls International)")},
            {"DE", new CompanyInfo("Industrials", "Manufacturer of agricultural, construction, and forestry machinery (Deere & Company)")},
            {"CMI", new CompanyInfo("Industrials", "Manufacturer of engines and power generation products (Cummins Inc.)")},
            {"CP", new CompanyInfo("Industrials", "Freight railway operator across North America (Canadian Pacific Kansas City)")},
            {"UNP", new CompanyInfo("Industrials", "Freight-hauling railway network (Union Pacific Corporation)")},
            {"NSC", new CompanyInfo("Industrials", "Freight railway operator in the Eastern United States (Norfolk Southern Corporation)")},
            {"ETN", new CompanyInfo("Industrials", "Power management company (Eaton Corporation plc)")},
            {"ROP", new CompanyInfo("Industrials", "Diversified industrial technology company (Roper Technologies)")},
            {"TT", new CompanyInfo("Industrials", "Construction materials and building solutions company (Trane Technologies plc)")},
            {"IR", new CompanyInfo("Industrials", "Industrial manufacturing company (Ingersoll Rand Inc.)")},
            {"HII", new CompanyInfo("Industrials", "Military shipbuilding and defense services (Huntington Ingalls Industries)")},
            {"ITW", new CompanyInfo("Industrials", "Diversified industrial manufacturer (Illinois Tool Works Inc.)")},
            {"SWK", new CompanyInfo("Industrials", "Tools and industrial products company (Stanley Black & Decker, Inc.)")},
            {"RSG", new CompanyInfo("Industrials", "Waste management company (Republic Services, Inc.)")},
            {"CPRT", new CompanyInfo("Industrials", "Online auto auction and remarketing services (Copart, Inc.)")},
            {"FAST", new CompanyInfo("Industrials", "Distributor of fasteners and industrial supplies (Fastenal Company)")},
            {"ALK", new CompanyInfo("Industrials", "Airline company (Alaska Air Group, Inc.)")},
            {"JBLU", new CompanyInfo("Industrials", "Airline company (JetBlue Airways Corporation)")},
            {"AAL", new CompanyInfo("Industrials", "Major American airline (American Airlines Group Inc.)")},
            {"ULCC", new CompanyInfo("Industrials", "Low-cost airline (Allegiant Travel Company)")},
            {"WCN", new CompanyInfo("Industrials", "Waste and environmental services (Waste Connections, Inc.)")},

            // --- 🏠 Real Estate & Utilities ---
            {"NEE", new CompanyInfo("Utilities", "Energy company, electric and gas utility (NextEra Energy)")},
            {"DUK", new CompanyInfo("Utilities", "Electric power and natural gas holding company (Duke Energy)")},
            {"SO", new CompanyInfo("Utilities", "Electric utility holding company (The Southern Company)")},
            {"D", new CompanyInfo("Utilities", "Electric, gas, and nuclear power utility (Dominion Energy)")},
            {"SRE", new CompanyInfo("Utilities", "Energy infrastructure company (Sempra Energy)")},
            {"EQIX", new CompanyInfo("Real Estate", "Data center and internet exchange provider (Equinix REIT)")},
            {"PLD", new CompanyInfo("Real Estate", "REIT specializing in logistics facilities (Prologis)")},
            {"AMT", new CompanyInfo("Real Estate", "REIT, owning and operating communications sites (American Tower)")},
            {"PCG", new CompanyInfo("Utilities", "Natural gas and electric utility (PG&E Corporation)")},
            {"EXR", new CompanyInfo("Real Estate", "Self-storage facilities REIT (Extra Space Storage)")},
            {"PSA", new CompanyInfo("Real Estate", "Self-storage facilities REIT (Public Storage)")},
            {"SPG", new CompanyInfo("Real Estate", "REIT specializing in shopping malls and other retail properties (Simon Property Group)")},
            {"O", new CompanyInfo("Real Estate", "REIT, commercial properties under long-term net lease agreements (Realty Income Corporation)")},
            {"EIX", new CompanyInfo("Utilities", "Electric power and natural gas utility (Edison International)")},
            {"AEP", new CompanyInfo("Utilities", "Electric utility holding company (American Electric Power)")},
            {"XEL", new CompanyInfo("Utilities", "Electric and natural gas utility (Xcel Energy Inc.)")},
            {"ED", new CompanyInfo("Utilities", "Regulated electric and gas utility (Consolidated Edison, Inc.)")},
            {"DTE", new CompanyInfo("Utilities", "Electric and natural gas utility (DTE Energy Company)")},
            {"FE", new CompanyInfo("Utilities", "Electric utility holding company (FirstEnergy Corp.)")},
            {"WEC", new CompanyInfo("Utilities", "Electric and natural gas utility (WEC Energy Group)")},
            {"WTRG", new CompanyInfo("Utilities", "Water and wastewater utility (Essential Utilities Inc.)")},
            {"PPL", new CompanyInfo("Utilities", "Electric and natural gas utility (PPL Corporation)")},
            {"BEP", new CompanyInfo("Utilities", "Renewable power and energy transition (Brookfield Renewable Partners L.P.)")},
            {"AWK", new CompanyInfo("Utilities", "Water and wastewater utility (American Water Works Company, Inc.)")},
        };

        public static CompanyInfo Get(string ticker)
        {
            // Ticker check is case-insensitive for robustness, though dictionary keys are uppercase
            return Descriptions.TryGetValue(ticker.ToUpper(), out var info) ? info : null;
        }
    }
}